### ISSUE TITLE
Exportarr support multiple instances, per app serviceMonitor config

### ISSUE THREAD

**Issue by hollanbm** [homeylab/helm-charts#82]
Thanks a ton for the chart btw, you saved me a bunch of time as I was starting to write my own.

I had some suggestions I wanted to pitch and see what your thoughts on them were.

I run multiple instances of radarr, and in order to work around this limitation, I just installed the chart a second time

I was thinking it would be nice if the chart supported this natively.

With the below, the object name would become `.Values.exportarr.apps.radarr.[0].name`. This way, you could preserve the loops and provide application-specific serviceMonitor configuration. For example, if someone wanted to alter the servicemonitor labels for one instance of radarr, but not the other.

```yaml
# values.yaml
exportarr:
  apps:
    radarr:
      - name: radarr
        url: ""
        # optional, use instead of `apiKey`
        # this secret should provide the `apiKey` used for auth
        # if auth is not required, do not provide any `secretKey` or `apiKey`
        existingSecret:
          # name of secret
          name: ""
          # name of key within secret to use
          # example: "radarr_api_key"
          secretKey: ""
        # ignored if `existingSecret` is used
        apiKey: ""
        extraEnv: {}
          # ENABLE_ADDITIONAL_METRICS: true
        ## Additional volumes on the output Deployment definition.
        volumes: []
        ## Additional volumeMounts on the output Deployment definition.
        volumeMounts: []
        metrics:
          enabled: true
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9707"
          serviceMonitor:
            enabled: false
            path: /metrics
            # how often to scrape
            interval: 4m
            scrapeTimeout: 90s
            additionalLabels: {}
            targetLabels: []
            # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint
            relabelings: []
            metricRelabelings: []
      - name: radarr-4k
        url: ""
        # optional, use instead of `apiKey`
        # this secret should provide the `apiKey` used for auth
        # if auth is not required, do not provide any `secretKey` or `apiKey`
        existingSecret:
          # name of secret
          name: ""
          # name of key within secret to use
          # example: "radarr_api_key"
          secretKey: ""
        # ignored if `existingSecret` is used
        apiKey: ""
        extraEnv: {}
          # ENABLE_ADDITIONAL_METRICS: true
        ## Additional volumes on the output Deployment definition.
        volumes: []
        ## Additional volumeMounts on the output Deployment definition.
        volumeMounts: []
        metrics:
          enabled: true
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9707"
          serviceMonitor:
            enabled: false
            path: /metrics
            # how often to scrape
            interval: 4m
            scrapeTimeout: 90s
            additionalLabels: {}
            targetLabels: []
            # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint
            relabelings: []
            metricRelabelings: []
```

**Comment by pchang388** [comment]
hey @hollanbm 

Thanks for opening this issue and providing a suggestion! I do think this would be helpful for those that run multiple instances. I like the idea and think it can be worked in. 

But this will be a breaking change for the chart and will need to be tested on my end. I will also need to ensure everything translates over as nicely as you described. Let me take a look when I get some time in the next few days and get back to you.

Thanks!

**Comment by pchang388** [comment]
Sorry for the delay, been a busy time period. I just wanted to let you know that I am taking a look at this and seeing how it could be implemented.

I have a local branch of your proposed change working for the most part but still looking into how to best handle some of the configuration options and setting defaults vs individual app metric properties. It's actually getting pretty messy with the inner loops and different places to override/set the same properties. I'll continue to see what I can do

**Comment by pchang388** [comment]
@hollanbm 

I have a pretty clean local version of it working that is fairly easy to maintain but not as easy to use. If an instance in the array has a `metrics` key and value, it will replace the global `metrics` object completely.

There are some downsides of going to the array and per object/instance `metric` fields:

You have to explicitly set all fields in each object/instance even if you want to use the default or else the chart template gets pretty ugly having to check that each key exists in the object/instance before being able to safely call it or assign a default if needed. Unless there's a better way to implement this logic - feedback welcome.

In the current version of the chart, for multiple instances the expectation is to use a different chart name when installing and a different `values.yaml` file. That can be somewhat tedious managing but it allows for easy usage and you can specify only what you need and let the defaults fill in the missing ones, example:
```yaml
exportarr:
    apps:
        radarr:
          enabled: true
          url: "https://radarr.test"
        sonarr:
          enabled: true
          url: "https://radarr.test"
```

Overall though I do think it is helpful for those that run many instances of an arr application - I will probably implement some variation of your requirements in a few days, thanks!

**Comment by hollanbm** [comment]
@pchang388 thanks for the update! Looking forward to it!

without seeing the pending chart changes, I don’t know if this helps at all. But here’s some things I’ve picked up that might be handy?

usually when I work on charts, I’ll throw the defaults into the charts values.yaml. It’s usually easier, but every so often I run into instances where the default function comes in handy.

```
drink: {{ .Values.favorite.drink | default "tea" | quote }}
``` 

I’ll also use toYaml, to drop the entire object contents into the rendered manifest directly

```
{{- toYaml .Values.envVars | nindent 12 -}}
```

**Comment by pchang388** [comment]
Hey @hollanbm thanks for the suggestions and definitely feel free to take a look if you have any input, 

I have a branch here with the changes I made and tested out locally: https://github.com/homeylab/helm-charts/tree/exportarr-2.0.0/charts/exportarr

It would definitely be nice able to simply set defaults but since we have to call individual keys within the `metrics` object, if you don't fill out the fields properly in `metrics` you can end up with a nil pointer. So the user has to explicitly set all fields even if they want the default.

For instance in `exportarr.apps.radarr[0].metrics` the user forgot to put a field like `...metrics.serviceMonitor` you would see:

```
Error: INSTALLATION FAILED: template: exportarr/templates/servicemonitor.yaml:11:38: executing "exportarr/templates/servicemonitor.yaml" at <$appMetrics.serviceMonitor.enabled>: nil pointer evaluating interface {}.enabled
```

So I want to do:
```
path: {{ $appMetrics.serviceMonitor.path | default $.Values.exportarr.metrics.serviceMonitor.path }}
```
But I can't unless I check each key beforehand using `hasKey` and then assigning to something to access safely later.

You could split it out and try to safely do it like below but it becomes quite tedious to maintain especially if you want to extend this logic to each `exportarr.apps.{arr_app}.[0]` properties like `url`, `apiKey`, etc.

Example: 
```yaml
{{- if (.Values.exportarr.metrics.enabled) }}
{{- range $instance_key, $instance_val := .Values.exportarr.apps }}
{{- range $app := $instance_val }}

# assign to default global `metrics` object
{{- $appMetrics := $.Values.exportarr.metrics -}}

# assign properties if present
{{- if $app.metrics }}
{{- if $app.metrics.podAnnotations }}
{{- $appMetrics.podAnnotations = $app.metrics.podAnnotations -}}
{{- if $app.metrics.serviceMonitor -}}
# ensure we don't assign a value if doesn't have `enabled` field, use global default if needed
{{- if (hasKey $app.metrics.serviceMonitor "enabled") }}
{{- $appMetrics.serviceMonitor.enabled = $app.metrics.serviceMonitor.enabled}}
{{- else }}
{{- $appMetrics.serviceMonitor.enabled = $.Values.exportarr.metrics.serviceMonitor.enabled -}}
{{- end }}
{{- $appMetrics.serviceMonitor.interval = $app.metrics.serviceMonitor.interval}}
...
...
...
...
{{- end }}
{{- end }}
{{- end }}
...
...
...
```

`toYaml` dropping could work for `metrics` but not so sure on `exportarr.apps.{arr_app}.[0]` instances themselves if that makes sense. Since they would have to define the deployment resources straight in there pretty much.

In the end, it's a trade off for having ability to add more instances and configure them easier. Having to list all the config explicitly might be the downside although I don't think it's too much of an issue if that limitation is mentioned upfront.

**Comment by pchang388** [comment]
Hey @hollanbm - I know this is probably way too late, but I had just a little bit of time and saw that my feature branch for this was actually almost done. 

I went ahead and implemented your requested feature in exportarr chart version `2.0.0`. You can now specify multiple instances under each key (`radarr`, `sonarr`, etc) in a list format and override the global metrics field as needed.

Example (full details on chart's readme):
```yaml
exportarr:
  apps:
    radarr:
    - name: main
      enabled: true
      url: ""
      apiKey: ""
      metrics:
        serviceMonitor:
          enabled: true
          path: /metrics
          # how often to scrape
          interval: 1m
          scrapeTimeout: 30s
          additionalLabels: {}
          targetLabels: []
          relabelings: []
          metricRelabelings: []
    sonarr:
    - name: main
      enabled: true
      url: ""
      apiKey: ""
      extraEnv:
        ENABLE_ADDITIONAL_METRICS: true
    prowlarr:
    - name: main
      enabled: true
      url: ""
      apiKey: ""
    bazarr:
    - name: main
      enabled: true
      url: ""
      apiKey: ""
```

I tried to make it as easy to override globals and configure each instance, was pretty tedious with helm templating flow control and using temp variables, but I think I found an implementation that is fairly flexible.

Sorry for the long delay, been busy and this got forgotten for a while. But hope it works for you, if not, please let me know of any issues - Thanks!
